version: "3.9"
services:
  db:
    image: postgres:15
    container_name: db_app
    command: -p 1221
    volumes:
      - ./postgres-data:/var/lib/postgresql
    expose:
      - 1221
    env_file:
      - docker.env_example
  app:
    build:
      context: .
    env_file:
      - docker.env_example
    container_name: fastapi_app
    command: ["/digest_service/docker/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db
