"""initial

Revision ID: d3fc5558a0c9
Revises: 
Create Date: 2023-07-22 00:43:45.019818

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d3fc5558a0c9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk__user")),
    )
    op.create_table(
        "digest",
        sa.Column("digest_id", sa.UUID(), nullable=False),
        sa.Column("user", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["user"], ["user.user_id"], name=op.f("fk__digest__user__user")),
        sa.PrimaryKeyConstraint("digest_id", name=op.f("pk__digest")),
    )
    op.create_table(
        "subscription",
        sa.Column("subscription_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("user", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["user"], ["user.user_id"], name=op.f("fk__subscription__user__user")),
        sa.PrimaryKeyConstraint("subscription_id", name=op.f("pk__subscription")),
    )
    op.create_table(
        "post",
        sa.Column("post_id", sa.UUID(), nullable=False),
        sa.Column("subscription", sa.UUID(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("popularity", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["subscription"], ["subscription.subscription_id"], name=op.f("fk__post__subscription__subscription")
        ),
        sa.PrimaryKeyConstraint("post_id", name=op.f("pk__post")),
    )
    op.create_table(
        "digest_post",
        sa.Column("digest_id", sa.UUID(), nullable=True),
        sa.Column("post_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["digest_id"], ["digest.digest_id"], name=op.f("fk__digest_post__digest_id__digest")),
        sa.ForeignKeyConstraint(["post_id"], ["post.post_id"], name=op.f("fk__digest_post__post_id__post")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("digest_post")
    op.drop_table("post")
    op.drop_table("subscription")
    op.drop_table("digest")
    op.drop_table("user")
    # ### end Alembic commands ###
